version: '3.8'

services:
  webapp:
    build:
      context: src/backend/EventPlanner
    ports:
      - 5094:5094
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5094
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=admin;Host=postgres;Port=5432;Database=event_planner;
      - ADMIN_EMAIL=admin@ibs.ru
      - ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - event_planner_network
    restart: always
  postgres:
    image: postgres:latest
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - event_planner_network
    restart: always
  react:
    build: 
      context: src/frontend/event-planner
    ports:
      - 80:3000
    environment:
      NODE_ENV: development
    restart: always

volumes:
    postgres-volume:
        external: false

networks:
  event_planner_network:
    external: false
    name: book-app-network
    driver: bridge